-- MySQL Script generated by MySQL Workbench
-- Fri May 10 01:30:07 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bdd_projet5
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdd_projet5
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdd_projet5` DEFAULT CHARACTER SET utf8 ;
USE `bdd_projet5` ;

-- -----------------------------------------------------
-- Table `bdd_projet5`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_projet5`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `role` ENUM('administrator', 'member') NOT NULL,
  `privilege` ENUM('None', 'In Progress', 'Done') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdd_projet5`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_projet5`.`article` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `art_content` TEXT(200) NOT NULL,
  `art_date_added` DATE NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_article_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `bdd_projet5`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_article_user1_idx` ON `bdd_projet5`.`article` (`user_id` ASC);


-- -----------------------------------------------------
-- Table `bdd_projet5`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_projet5`.`comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(45) NOT NULL,
  `content` TEXT(500) NOT NULL,
  `date_added` DATE NOT NULL,
  `status` ENUM('Accepted', 'declined', 'waiting') NOT NULL,
  `article_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_comment_article`
    FOREIGN KEY (`article_id`)
    REFERENCES `bdd_projet5`.`article` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_comment_article_idx` ON `bdd_projet5`.`comment` (`article_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
